### ISSUE TITLE
As a user when I link items to my account using Plaid Link I expect the access_token to be persisted to the database.

### ISSUE THREAD

**Issue by jpdaprato** [cygnustechnologies/pocket-goblin-client#47]

**Comment by deduced** [comment]
Ok - we store the access token in the ITEM entity in the database. When we talk we can review if that's the place for it or not. 


![Screen Shot 2018-10-06 at 2.29.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b8f01ee10a5c500128d240f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f56b7191a37af110224f5b5c5ecc3c4a4356bcbbd671f3e57862804e0ebf803e5b76c73519feea871ebc01ba26da4a84b3bedc44d2f42f67b6d5db1063474f4dcbed5727a19141c95df543e94953ad1a3464ef732431.png)
